### ISSUE TITLE
apply: Determine blocking status of dependent bugs based on arch

### ISSUE THREAD

**Issue by mgorny** [mgorny/nattka#27]
Right now open dependent bugs block us unconditionally. It would be better to do this only if it is pending on our arch, and otherwise ignore it.

**Comment by asarubbo** [comment]
I approve this enhancement, however I would like to point out something else.

Atm, the fastest way to do that, is to check the "Hardware" field and on the other side, the "Hardware" field should point to the hardware where the failure happens.

At this point when the blocker bug is reproducible on "ppc and arm" but passed on "amd64, x86 and ppc64" the hardware field does not allows to have more than one choice.

So, before working on this, what do you think about have a custom field like "Reproducible on arch" which allows us to specify all arches where the issue happen?

**Comment by mgorny** [comment]
Actually, this is about keywording bugs depending on other keywording bugs. Package bugs are a bigger problem, as you note, and it's far on my todo.
