### ISSUE TITLE
Only comment on security bugs with [stable] in whiteboard

### ISSUE THREAD

**Issue by thesamesam** [mgorny/nattka#31]
Security bugs should only be commented on with [stable] in whiteboard - and possibly [stable?].

This would avoid situations like in this [bug](https://bugs.gentoo.org/716644#c7) where comments are posted by nattka causing unnecessary emails, even once the stabilisation part is done.

**Comment by mgorny** [comment]
Is that a reliable metric? Wouldn't it be confusing if people forgot to set it and NATTkA would silently ignore the bug?

**Comment by Whissi** [comment]
Yes, it's a reliable metric. Maybe not the position but it's reliable to check if whiteboard contains the word "stable".

**Comment by mgorny** [comment]
I'd personally prefer trying to solve this via #32. My main concern is that this solution relies entirely on the last arch team removing 'stable' from whiteboard. If that doesn't happen, nattka will still comment in the window before security team removes it.

**Comment by mgorny** [comment]
Is the solution from #32 working good enough? Please monitor it for some time, and either close the bug or lemme know to implement this one in addition to it.

**Comment by mgorny** [comment]
Please reopen if you feel there's still a need for this.
