### ISSUE TITLE
Expand `*` on sanity-check+

### ISSUE THREAD

**Issue by mgorny** [mgorny/nattka#34]
CC @derdakon, @asarubbo

The idea is to solve two problems:
1. Meaning of `*` changes when old versions are removed (i.e. exp arches disappear).
2. Compatibility with old tooling.

My proposed solution would be to expand `*` (and maybe `^`) on transition to `sanity-check+` (i.e. when package list is supposedly ready).

A side effect would be that `*` would no longer adapt to parallel keywording and stabilization. Right now if a single version is both target of rekeywording and stabilization, the arch becomes stabilization target via `*` as soon as it gets `~arch` keyword. Not sure if that's desirable or not.

**Comment by DerDakon** [comment]
Are there really any bugs where this happens in parallel? All I remember were one or the other, and if both was needed the stabilization bug depended on the keywording one.

After determining the list of arches to CC in a bug I would entirely remove the '*' for those lines where it would match the complete CC list. This has the advantage that I can later use the same bug for another arch that was previously not CC'ed. All other lists would behave the same: if they match the CC list they would just be empty, if they contain a subset then that would be explicitely stated.

**Comment by mgorny** [comment]
> Are there really any bugs where this happens in parallel? All I remember were one or the other, and if both was needed the stabilization bug depended on the keywording one.

It's pretty common for Python packages to be stabilized before most of arches manage to keyword the new version.

> After determining the list of arches to CC in a bug I would entirely remove the '*' for those lines where it would match the complete CC list. This has the advantage that I can later use the same bug for another arch that was previously not CC'ed. All other lists would behave the same: if they match the CC list they would just be empty, if they contain a subset then that would be explicitely stated.

I suppose that could work if we use `CC-ARCHES` but otherwise I wouldn't make too far going assumptions.
