### ISSUE TITLE
`nattka commit` fails if some of the packages are done already

### ISSUE THREAD

**Issue by mgorny** [mgorny/nattka#44]
`nattka commit` logic can't distinguish packages done already vs packages waiting for commit. As a result, it spawns `git commit` on files with no changes and fails.

**Comment by mattst88** [comment]
Confirmed with bug 700918:

    nattka apply -a alpha 700918
    nattka commit -a alpha 700918

where the package list is

    dev-python/virtualenv
    dev-python/distlib
    dev-python/towncrier
    dev-python/click-default-group

where only virtualenv and distlib need alpha keywords.
