### ISSUE TITLE
Honor the 30-day-rule via nattka

### ISSUE THREAD

**Issue by juippis** [mgorny/nattka#53]
Hi, 

just an idea. Is it possible for nattka to fail sanity check if the package in question hasn't been untouched for at least 30 days AND it's not a security bug? I know *pkgcheck*'s `StableRequestCheck` would show it, but it doesn't work on packages without prior stable keywords.

Does this sound reasonable? Humans make too much errors.

**Comment by thesamesam** [comment]
I'd prefer a warning or requirement for some keyword to allow us to override this for e.g. urgent bug fixes, regressions, or where stable is just in a rotten state (thinking of things like OCaml).

I like the idea though, definitely.

**Comment by juippis** [comment]
Hmm yeah maybe failing sanity check is too harsh. Nattka writing a warning comment could probably suffice, same way as it does when dep calculation fails.

**Comment by mgorny** [comment]
I don't think this is a good idea. Developers should be allowed to decide when to stabilize stuff, and 30-day rule is just a weak guideline. Making it fail by default is just wrong, and I see no purpose in emitting a meaningless warning. Having it opt-in just doesn't make any sense, unless you see it as a way to make NATTkA auto-start stabilization after N days but I'm not convinced this is worth the effort.

**Comment by juippis** [comment]
> unless you see it as a way to make NATTkA auto-start stabilization after N days but I'm not convinced this is worth the effort.

Something like this is in the planning, but more on that later.
