### ISSUE TITLE
Mark old sanity-check/dep output as obsolete using tags

### ISSUE THREAD

**Issue by thesamesam** [mgorny/nattka#54]
Bugzilla lets us tag comments as obsolete which automatically folds them. This is really helpful when scrolling through sometimes long keywording or stabilisation bugs.

[Example](https://bugs.gentoo.org/748576) screenshot of when a comment is tagged obsolete:
<img width="1269" alt="Screenshot 2020-10-18 at 16 55 38" src="https://user-images.githubusercontent.com/11667869/96373187-c127a480-1162-11eb-9d8c-2e307c4a8f97.png">

**Comment by mgorny** [comment]
This certainly wouldn't be that hard. We'd have to grab all comments by creator (we already take the latest comment from the list, so that's nothing really new), and use https://bugzilla.readthedocs.io/en/latest/api/core/v1/comment.html#update-comment-tags to update them.
