### ISSUE TITLE
Race conditions with Bugzilla

### ISSUE THREAD

**Issue by mgorny** [mgorny/nattka#61]
Things like https://bugs.gentoo.org/779535#c8 can't be explained otherwise than through race conditions inside Bugzilla. Updates seem to be atomic, our replication is supposed to be atomic, so the only reasonable explanation is that the bug state (probably custom fields) are gotten via multiple SELECTs, and the database state can change in the middle.

So far the only solution I can think of is hoping that 'update timestamp' gets written first, and ignoring 'very freshly updated' bugs.

**Comment by thesamesam** [comment]
FWIW I’ve seen exactly this via saved searches for open stabilisation bugs. If I run e.g. nattka resolve on a bunch of bugs and keep refreshing my search, I’ll see bugs with FIXED in the list.

**Comment by mgorny** [comment]
Fixed in 1d886c79a3273a195c63b28e638f71a24085fe06, and backported to 0.2.11.1.
